node {

    def mvnHome = tool 'M3'

    stage ('Checkout') {
        checkout scm
    }

    stage ('Compile') {
        sh "${mvnHome}/bin/mvn clean install -DskipTests"
    }

    stage ('Test') {
        sh "${mvnHome}/bin/mvn test"
    }

    stage('Publish') {
        sh "echo I am publishing"
    }
}
